# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150610201813) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "users", force: true do |t|
    t.string   "domain_name"
    t.string   "name_first"
    t.string   "name_last"
    t.text     "homepage_header"
    t.text     "intro_paragraph"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "homepage_pic_file_name"
    t.string   "homepage_pic_content_type"
    t.integer  "homepage_pic_file_size"
    t.datetime "homepage_pic_updated_at"
    t.string   "about_pic_file_name"
    t.string   "about_pic_content_type"
    t.integer  "about_pic_file_size"
    t.datetime "about_pic_updated_at"
    t.string   "resume_file_name"
    t.string   "resume_content_type"
    t.integer  "resume_file_size"
    t.datetime "resume_updated_at"
    t.integer  "background_type"
    t.string   "background_img1_file_name"
    t.string   "background_img1_content_type"
    t.integer  "background_img1_file_size"
    t.datetime "background_img1_updated_at"
    t.string   "background_img2_file_name"
    t.string   "background_img2_content_type"
    t.integer  "background_img2_file_size"
    t.datetime "background_img2_updated_at"
    t.string   "background_img3_file_name"
    t.string   "background_img3_content_type"
    t.integer  "background_img3_file_size"
    t.datetime "background_img3_updated_at"
    t.string   "background_img4_file_name"
    t.string   "background_img4_content_type"
    t.integer  "background_img4_file_size"
    t.datetime "background_img4_updated_at"
    t.string   "background_link1"
    t.string   "background_link2"
    t.string   "background_link3"
    t.string   "background_link4"
    t.integer  "showcase_type"
    t.string   "project1_title"
    t.text     "project1_paragraph"
    t.string   "project2_title"
    t.text     "project2_paragraph"
    t.string   "project3_title"
    t.text     "project3_paragraph"
    t.string   "project4_title"
    t.text     "project4_paragraph"
    t.string   "project1_file1_file_name"
    t.string   "project1_file1_content_type"
    t.integer  "project1_file1_file_size"
    t.datetime "project1_file1_updated_at"
    t.string   "project1_file2_file_name"
    t.string   "project1_file2_content_type"
    t.integer  "project1_file2_file_size"
    t.datetime "project1_file2_updated_at"
    t.string   "project1_file3_file_name"
    t.string   "project1_file3_content_type"
    t.integer  "project1_file3_file_size"
    t.datetime "project1_file3_updated_at"
    t.string   "project2_file1_file_name"
    t.string   "project2_file1_content_type"
    t.integer  "project2_file1_file_size"
    t.datetime "project2_file1_updated_at"
    t.string   "project2_file2_file_name"
    t.string   "project2_file2_content_type"
    t.integer  "project2_file2_file_size"
    t.datetime "project2_file2_updated_at"
    t.string   "project2_file3_file_name"
    t.string   "project2_file3_content_type"
    t.integer  "project2_file3_file_size"
    t.datetime "project2_file3_updated_at"
    t.string   "project3_file1_file_name"
    t.string   "project3_file1_content_type"
    t.integer  "project3_file1_file_size"
    t.datetime "project3_file1_updated_at"
    t.string   "project3_file2_file_name"
    t.string   "project3_file2_content_type"
    t.integer  "project3_file2_file_size"
    t.datetime "project3_file2_updated_at"
    t.string   "project3_file3_file_name"
    t.string   "project3_file3_content_type"
    t.integer  "project3_file3_file_size"
    t.datetime "project3_file3_updated_at"
    t.string   "project4_file1_file_name"
    t.string   "project4_file1_content_type"
    t.integer  "project4_file1_file_size"
    t.datetime "project4_file1_updated_at"
    t.string   "project4_file2_file_name"
    t.string   "project4_file2_content_type"
    t.integer  "project4_file2_file_size"
    t.datetime "project4_file2_updated_at"
    t.string   "project4_file3_file_name"
    t.string   "project4_file3_content_type"
    t.integer  "project4_file3_file_size"
    t.datetime "project4_file3_updated_at"
    t.string   "project1_file1_title"
    t.integer  "project1_file1_type"
    t.string   "project1_file2_title"
    t.integer  "project1_file2_type"
    t.string   "project1_file3_title"
    t.integer  "project1_file3_type"
    t.string   "project2_file1_title"
    t.integer  "project2_file1_type"
    t.string   "project2_file2_title"
    t.integer  "project2_file2_type"
    t.string   "project2_file3_title"
    t.integer  "project2_file3_type"
    t.string   "project3_file1_title"
    t.integer  "project3_file1_type"
    t.string   "project3_file2_title"
    t.integer  "project3_file2_type"
    t.string   "project3_file3_title"
    t.integer  "project3_file3_type"
    t.string   "project4_file1_title"
    t.integer  "project4_file1_type"
    t.string   "project4_file2_title"
    t.integer  "project4_file2_type"
    t.string   "project4_file3_title"
    t.integer  "project4_file3_type"
    t.string   "tumblr_url"
  end

end
